version: '3.8'

services:
  web:
    build: .
    container_name: meu-projeto-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - minha-rede
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: meu-projeto-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tarefas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  db_data:
